INSERT INTO roles VALUES (nextval('role_seq_gen'), 'ROLE_ADMIN');
INSERT INTO roles VALUES (nextval('role_seq_gen'), 'ROLE_USER');
INSERT INTO roles VALUES (nextval('role_seq_gen'), 'ROLE_TRAINER');

INSERT INTO users VALUES (nextval('user_seq_gen'), 'Nikolina', 'Pavkovic', '$2a$10$vl8bE7gOmlXJ4otSv5t1aeW9/9fAvcwunPqIPrCQyWY.If2v0ZbL6', '0658886407', 'pavkovicn@hotmail.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Milos', 'Milosevic', '$2a$10$Hc5OZFSMJNeRnWayZe29n./m2iyOS1camXVR.HCVpHaLMgsyjw4k.', '0637319010', 'pavkovicn51@gmail.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Marija', 'Maric', '$2a$10$OjKPmk.DpQa5iIA27CC4oOz4RQeJBiKzg5qVe7fXebfPCklsGOoNe', '0643813711', 'fishingbookernsm@hotmail.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Mirko', 'Miric', '$2a$10$OjKPmk.DpQa5iIA27CC4oOz4RQeJBiKzg5qVe7fXebfPCklsGOoNe', '0643813711', 'mirko@mirko.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Petar', 'Petrovic', '$2a$10$OjKPmk.DpQa5iIA27CC4oOz4RQeJBiKzg5qVe7fXebfPCklsGOoNe', '0643813711', 'petar@petar.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Goran', 'Gogic', '$2a$10$OjKPmk.DpQa5iIA27CC4oOz4RQeJBiKzg5qVe7fXebfPCklsGOoNe', '0643813711', 'goran@goran.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Senka', 'Senic', '$2a$10$OjKPmk.DpQa5iIA27CC4oOz4RQeJBiKzg5qVe7fXebfPCklsGOoNe', '0643813711', 'senka@gmail.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Saska', 'Radic', '$2a$10$OjKPmk.DpQa5iIA27CC4oOz4RQeJBiKzg5qVe7fXebfPCklsGOoNe', '0643813711', 'saska@hotmail.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Milica', 'Mitic', '$2a$10$OjKPmk.DpQa5iIA27CC4oOz4RQeJBiKzg5qVe7fXebfPCklsGOoNe', '0643813711', 'milica@hotmail.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Stefan', 'Stefic', '$2a$10$OjKPmk.DpQa5iIA27CC4oOz4RQeJBiKzg5qVe7fXebfPCklsGOoNe', '0643813711', 'stefan@hotmail.com');
INSERT INTO users VALUES (nextval('user_seq_gen'), 'Nikola', 'Nikolic', '$2a$10$OjKPmk.DpQa5iIA27CC4oOz4RQeJBiKzg5qVe7fXebfPCklsGOoNe', '0643813711', 'nikola@hotmail.com');

INSERT INTO users_roles VALUES (1,1);
INSERT INTO users_roles VALUES (2,3);
INSERT INTO users_roles VALUES (3,2);
INSERT INTO users_roles VALUES (4,3);
INSERT INTO users_roles VALUES (5,2);
INSERT INTO users_roles VALUES (6,3);
INSERT INTO users_roles VALUES (7,2);
INSERT INTO users_roles VALUES (8,2);
INSERT INTO users_roles VALUES (9,2);
INSERT INTO users_roles VALUES (10,3);
INSERT INTO users_roles VALUES (11,2);

INSERT INTO benefits VALUES (nextval('benefit_seq_gen'), 'Neograničeno korišćenje teretane 30 dana');
INSERT INTO benefits VALUES (nextval('benefit_seq_gen'), 'Neograničeno posećivanje grupnih treninga 30 dana');
INSERT INTO benefits VALUES (nextval('benefit_seq_gen'), 'Preko 40 kardio sprava');
INSERT INTO benefits VALUES (nextval('benefit_seq_gen'), 'Uvodni trening');
INSERT INTO benefits VALUES (nextval('benefit_seq_gen'), 'Savetovanje');
INSERT INTO benefits VALUES (nextval('benefit_seq_gen'), 'Neograničeno korišćenje teretane 90 dana');
INSERT INTO benefits VALUES (nextval('benefit_seq_gen'), 'Neograničeno posećivanje grupnih treninga 90 dana');

INSERT INTO memberships VALUES (nextval('membership_seq_gen'), 30, 'Code 30 gym', 2500);
INSERT INTO memberships VALUES (nextval('membership_seq_gen'), 30, 'Code 30 grupni treninzi', 2500);
INSERT INTO memberships VALUES (nextval('membership_seq_gen'), 30, 'Code 30 gym + grupni treninzi', 3000);
INSERT INTO memberships VALUES (nextval('membership_seq_gen'), 90, 'Code 90 gym', 6000);
INSERT INTO memberships VALUES (nextval('membership_seq_gen'), 90, 'Code 90 grupni treninzi', 6000);
INSERT INTO memberships VALUES (nextval('membership_seq_gen'), 90, 'Code 90 gym + grupni treninzi', 7500);

INSERT INTO memberships_benefits VALUES (1,1);
INSERT INTO memberships_benefits VALUES (1,3);
INSERT INTO memberships_benefits VALUES (1,4);
INSERT INTO memberships_benefits VALUES (1,5);
INSERT INTO memberships_benefits VALUES (2,2);
INSERT INTO memberships_benefits VALUES (2,4);
INSERT INTO memberships_benefits VALUES (2,5);
INSERT INTO memberships_benefits VALUES (3,1);
INSERT INTO memberships_benefits VALUES (3,2);
INSERT INTO memberships_benefits VALUES (3,3);
INSERT INTO memberships_benefits VALUES (3,4);
INSERT INTO memberships_benefits VALUES (3,5);
INSERT INTO memberships_benefits VALUES (4,6);
INSERT INTO memberships_benefits VALUES (4,3);
INSERT INTO memberships_benefits VALUES (4,4);
INSERT INTO memberships_benefits VALUES (4,5);
INSERT INTO memberships_benefits VALUES (5,7);
INSERT INTO memberships_benefits VALUES (5,4);
INSERT INTO memberships_benefits VALUES (5,5);
INSERT INTO memberships_benefits VALUES (6,6);
INSERT INTO memberships_benefits VALUES (6,7);
INSERT INTO memberships_benefits VALUES (6,3);
INSERT INTO memberships_benefits VALUES (6,4);
INSERT INTO memberships_benefits VALUES (6,5);

INSERT INTO user_memberships VALUES (nextval('user_mem_seq_gen'),'2022-07-25 15:10:49.239', false, '2022-06-25 15:10:49.239', 1, 3);
INSERT INTO user_memberships VALUES (nextval('user_mem_seq_gen'),'2022-09-25 15:10:49.239', false, '2022-08-25 15:10:49.239', 2, 3);
INSERT INTO user_memberships VALUES (nextval('user_mem_seq_gen'),'2022-09-25 15:10:49.239', false, '2022-08-25 15:10:49.239', 3, 7);
INSERT INTO user_memberships VALUES (nextval('user_mem_seq_gen'),'2022-09-25 15:10:49.239', false, '2022-08-25 15:10:49.239', 4, 8);

INSERT INTO trainings VALUES (nextval('training_seq_gen'), 20, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu.', 45, 'Power Fit','2022-09-01 15:00:49.239', 2);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 30, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu.', 30, 'Insanity','2022-09-01 17:00:49.239', 4);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 20, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 45, 'Strong Nation','2022-09-02 18:00:49.239', 6);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 10, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 60, 'Yoga','2022-09-02 15:00:49.239', 10);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 15, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 45, 'Funkcionalni Fitness','2022-09-03 15:00:49.239', 2);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 30, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 30, 'Military Bootcamp','2022-09-01 12:00:49.239', 4);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 30, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 30, 'Core','2022-09-01 09:00:49.239', 2);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 25, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 60, 'Body Pump','2022-08-25 16:00:49.239', 2);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 20, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 30, 'HIIT','2022-08-26 15:00:49.239', 6);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 30, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 60, 'Yoga','2022-08-28 20:10:49.239', 6);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 35, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 45, 'Power Fit','2022-08-29 08:00:49.239', 6);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 35, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 60, 'Body Pump','2022-07-25 15:30:49.239', 6);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 25, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 30, 'Insanity','2022-09-01 07:10:49.239', 10);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 10, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 45, 'RPM','2022-08-30 13:00:49.239', 10);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 10, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 45, 'RPM','2022-08-30 14:00:49.239', 10);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 15, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 30, 'Insanity','2022-08-31 10:10:49.239', 4);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 20, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 30, 'HIIT','2022-08-22 15:00:49.239', 2);
INSERT INTO trainings VALUES (nextval('training_seq_gen'), 20, 'Trening je koncipiran da se vezbama snage, malog intenziteta i velikog broja ponavljanja, smanji procenat masti u korist misica i time poveca bazalni metabolizam, uz veliku potrosnju kalorija na samom treningu. ', 60, 'Yoga','2022-09-05 19:15:49.239', 2);

INSERT INTO trainings_reservations VALUES (1,3);
INSERT INTO trainings_reservations VALUES (1,5);
INSERT INTO trainings_reservations VALUES (1,7);
INSERT INTO trainings_reservations VALUES (1,8);
INSERT INTO trainings_reservations VALUES (1,9);
INSERT INTO trainings_reservations VALUES (1,11);
INSERT INTO trainings_reservations VALUES (2,3);
INSERT INTO trainings_reservations VALUES (2,5);
INSERT INTO trainings_reservations VALUES (2,7);
INSERT INTO trainings_reservations VALUES (2,8);
INSERT INTO trainings_reservations VALUES (3,3);
INSERT INTO trainings_reservations VALUES (3,5);
INSERT INTO trainings_reservations VALUES (3,11);
INSERT INTO trainings_reservations VALUES (4,7);
INSERT INTO trainings_reservations VALUES (4,8);
INSERT INTO trainings_reservations VALUES (5,9);
INSERT INTO trainings_reservations VALUES (5,11);
INSERT INTO trainings_reservations VALUES (5,3);
INSERT INTO trainings_reservations VALUES (5,5);
INSERT INTO trainings_reservations VALUES (6,3);
INSERT INTO trainings_reservations VALUES (6,5);
INSERT INTO trainings_reservations VALUES (6,7);
INSERT INTO trainings_reservations VALUES (7,8);
INSERT INTO trainings_reservations VALUES (7,9);
INSERT INTO trainings_reservations VALUES (7,11);
INSERT INTO trainings_reservations VALUES (7,5);
